#pragma once
#define ERROR_ARCARDE_SERVER_BAD_COMMAND 404
#define ERROR_ARCARDE_SERVER_BAD_FORMATING 405
#define ERROR_ARCARDE_SERVER_READING_MESSAGE 406
#define ERROR_ARCARDE_SERVER_ROUTE_NOT_FOUND 407
#define ERROR_ARCARDE_SERVER_BAD_ARGUMENTS 408



#define CONNECTION_SUCCESS 200
